config/routes.rb
Hackathon13Carpool::Application.routes.draw do
 

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  resources :routes

  resources :resource_schedules

resources :users do
   get 'addResource'

   resources :user_resources do
   end
   resources :preferences
end

  resources :homes do
    get 'register'

    get 'start', :on => :collection
    
  end

  get '/findcar' => 'resource_schedules#findcar', :as => 'findcar' 
  post '/findcar' => 'resource_schedules#searchcar', :as => 'findcar'

  get '/findpassenger' => 'resource_schedules#findpass', :as => 'findpassenger' 
  post '/findpassenger' => 'resource_schedules#searchpass', :as => 'findpassenger'

  get '/search' => 'resource_schedules#startsearch', :as => 'startsearch' 
  get '/find' => 'resource_schedules#find', :as => 'find' 
  post '/find' => 'resource_schedules#find', :as => 'find' 
  

   root :to => 'homes#index'

end

app/models/resource_schedule.rb
class ResourceSchedule < ActiveRecord::Base
  attr_accessible :available, :destination, :isconfirmed, :ishireconfirmed, :isowner, 
  :isreadytohire, :routeno, :startplace, :starttime, :userId, :userResourceId, :acNonac
  belongs_to :user, :foreign_key => "userId"
  accepts_nested_attributes_for :user


  def self.search start, dest, ispas
  	if ispas == "1"
  		results = ResourceSchedule.where(startplace: start ).where(destination: dest).where(isowner: false)
  	else
  		results = ResourceSchedule.where(startplace: start ).where(destination: dest).where(isowner: true)
  	end
  	#results = ResourceSchedule.all
    results.joins(:user).includes(:user)
  end

  def self.searchuser iduser, ispas
  	if ispas == "0"
  		results = ResourceSchedule.where(isowner: false).where(userId: iduser)
  	else
  		results = ResourceSchedule.where(isowner: true).where(userId: iduser)
  	end
  end
end

app/controllers/resource_schedules_controller.rb
class ResourceSchedulesController < ApplicationController
  # GET /resource_schedules
  # GET /resource_schedules.json
  def index
    @resource_schedules = ResourceSchedule.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @resource_schedules }
    end
  end

  def find
    @resource_schedule = ResourceSchedule.new

    @searchcriteria = "pass"
    if(params[:ispas] =="0")
    	@searchcriteria = "car"
    end

    #@query = SearchParam.new
    #@query.start = params[:start] unless params[:start].nil?
    #@query.dest = params[:start] unless params[:start].nil?

    @results = ResourceSchedule.search params[:start], params[:dest], params[:ispas]
    
    respond_to do |format|
      format.js
    end
  end

  # GET /resource_schedules/1
  # GET /resource_schedules/1.json
  def show
    @resource_schedule = ResourceSchedule.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @resource_schedule }
    end
  end

  # GET /resource_schedules/new
  # GET /resource_schedules/new.json
  def new
    @resource_schedule = ResourceSchedule.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @resource_schedule }
    end
  end

  # GET /resource_schedules/1/edit
  def edit
    @resource_schedule = ResourceSchedule.find(params[:id])
  end

  # POST /resource_schedules
  # POST /resource_schedules.json
  def create
    @resource_schedule = ResourceSchedule.new(params[:resource_schedule])

    respond_to do |format|
      if @resource_schedule.save
        format.html { redirect_to @resource_schedule, notice: 'Resource schedule was successfully created.' }
        format.json { render json: @resource_schedule, status: :created, location: @resource_schedule }
      else
        format.html { render action: "new" }
        format.json { render json: @resource_schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /resource_schedules/1
  # PUT /resource_schedules/1.json
  def update
    @resource_schedule = ResourceSchedule.find(params[:id])

    respond_to do |format|
      if @resource_schedule.update_attributes(params[:resource_schedule])
        format.html { redirect_to @resource_schedule, notice: 'Resource schedule was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @resource_schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resource_schedules/1
  # DELETE /resource_schedules/1.json
  def destroy
    @resource_schedule = ResourceSchedule.find(params[:id])
    @resource_schedule.destroy

    respond_to do |format|
      format.html { redirect_to resource_schedules_url }
      format.json { head :no_content }
    end
  end

  # POST /resource_schedules
  # POST /resource_schedules.json
  def searchcar
    @resource_schedule = ResourceSchedule.new(params[:resource_schedule])
    logger.info params
    @resource_schedule.userId = current_user.id
    @resource_schedule.startplace = params[:startplace]
    @resource_schedule.destination = params[:destination]
    @resource_schedule.isowner = false
    @resource_schedule.isconfirmed = false
    @resource_schedule.ishireconfirmed = false
    @resource_schedule.starttime = DateTime.parse(params[:resource_schedule_startdate].to_s + " " + params[:resource_schedule_starttime].to_s, "%d/%m/%Y %H-%M")

    # TODO: We should not be saving this. But, we should just show the results, and give the option to save it
    respond_to do |format|
      if @resource_schedule.save
        format.html { redirect_to startsearch_path, notice: 'Resource schedule was successfully created.' }
        format.json { render json: startsearch_path, status: :created, location: @resource_schedule }
      else
        format.html { redirect_to startsearch_path, notice: 'Unable to add it to listing' }
        format.json { render json: @resource_schedule.errors, status: :created, location: @resource_schedule }
      end
    end
  end

  def startsearch
    @resource_schedule = ResourceSchedule.new

    # TODO: Filter my Resource Schedules based on user id and date time
    @searchcriteria = "car"
    @isowner = "1"
    if(params[:q] =="fc") #Find Car
    	@searchcriteria = "car"
     	@isowner = "0"
    elsif (params[:q] =="fp") #Find Passenger
     	@searchcriteria = "pass"
	@isowner = "1"
    elsif(params[:q]=="gh") #Group Hire
	 @searchcriteria = "group"
    else
        @searchcriteria = "car"
     	@isowner = "0"
    end

    @myresource_schedules = ResourceSchedule.searchuser current_user.id, @isowner

    @display = "results"
    if(params[:listid].nil?)
        @display = "empty"
	@defdate = Date.today.strftime("%d/%m/%Y")
	@deftime = (Time.now + 30.minutes).strftime("%H:%M")
    else 
	@schedule = ResourceSchedule.find(params[:listid])
	@results = ResourceSchedule.search @schedule.startplace, @schedule.destination, @isowner
	@defstartplace = @schedule.startplace
	@defdest = @schedule.destination
	@defdate = @schedule.starttime.strftime("%d/%m/%Y")
	@deftime = @schedule.starttime.strftime("%H:%M")

	@resource_schedule = ResourceSchedule.new
    end
  end
  
   def findcar
	@resource_schedule = ResourceSchedule.new

	# TODO: Filter my Resource Schedules based on user id and date time
	@myresource_schedules = ResourceSchedule.all
	render 'findcar'
   end

  def findpass
  	@resource_schedule = ResourceSchedule.new

  	# TODO: Filter my Resource Schedules based on user id and date time
  	@myresource_schedules = ResourceSchedule.all
  	render 'findpass'
   end

  # POST /resource_schedules
  # POST /resource_schedules.json
  def searchpass
    @resource_schedule = ResourceSchedule.new(params[:resource_schedule])
    @resource_schedule.userId = current_user.id
    @resource_schedule.startplace = params[:startplace]
    @resource_schedule.destination = params[:destination]
    @resource_schedule.acNonac = params[:resource_schedule_isacnonac]
    @resource_schedule.isowner = true
    @resource_schedule.isconfirmed = true
    @resource_schedule.ishireconfirmed = false
    @resource_schedule.starttime = DateTime.parse(params[:resource_schedule_startdate].to_s + " " + params[:resource_schedule_starttime].to_s, "%d/%m/%Y %H-%M")

    # TODO: Save this and search for passengers
    respond_to do |format|
      if @resource_schedule.save
        format.html { redirect_to "/search?q=fp", notice: 'Listing has been successfully added.' }
        format.json { render json: startsearch_path, status: :created, location: @resource_schedule }
      else
        format.html { redirect_to startsearch_path, notice: 'Listing has not been added.'  }
        format.json { render json: @resource_schedule.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/resource_schedules_helper.rb
module ResourceSchedulesHelper
end

app/views/resource_schedules/_carresults.html.erb
<h4><%= pluralize(@results.count,"Match") %> Found</h4> <br/>

  <table class="table  table-striped">
    <tr>
      <th>&nbsp;</th>
      <th>Name</th>
<!--       <th>Isowner</th>
 -->
      <th>From</th>
      <th>To</th>
      <th>Start Time</th>
      
      <th>Seat(s) Available</th>
      <th></th>      
    </tr>

  <% @results.each do |r| %>
    <tr>
      <td><%= image_tag(r.user.image_url, :height=>35, :width=>35) %></td>
      <td><a href="<%='http://www.facebook.com/'+r.user.uid%>"  target="_blank"><i class="icon-facebook-sign"></i></a> &nbsp;<%= r.user.name %></td>
<!--       <td>
        <% if r.isowner == 0 %>
          <%= image_tag("Close-2-icon.png") %>
        <%else%>
          <%= image_tag("Ok-icon.png") %>
        <%end%>
      </td>
 -->
      <td><%= r.startplace %></td>
      <td><%= r.destination %></td>
      <td><%= r.starttime %></td>
      <td><%= r.available %></td>
      <td><a href="#" class="btn btn-danger active"><i class="icon-white icon-play"></i> Request</a></td>      
    </tr>
  <% end %>
  </table>

app/views/resource_schedules/_form.html.erb
<%= form_for(@resource_schedule) do |f| %>
  <% if @resource_schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource_schedule.errors.count, "error") %> prohibited this resource_schedule from being saved:</h2>

      <ul>
      <% @resource_schedule.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :userResourceId %><br />
    <%= f.number_field :userResourceId %>
  </div>
  <div class="field">
    <%= f.label :userId %><br />
    <%= f.number_field :userId %>
  </div>
  <div class="field">
    <%= f.label :isowner %><br />
    <%= f.number_field :isowner %>
  </div>
  <div class="field">
    <%= f.label :startplace %><br />
    <%= f.text_field :startplace %>
  </div>
  <div class="field">
    <%= f.label :destination %><br />
    <%= f.text_field :destination %>
  </div>
  <div class="field">
    <%= f.label :starttime %><br />
    <%= f.datetime_select :starttime %>
  </div>
  <div class="field">
    <%= f.label :routeno %><br />
    <%= f.number_field :routeno %>
  </div>
  <div class="field">
    <%= f.label :available %><br />
    <%= f.number_field :available %>
  </div>
  <div class="field">
    <%= f.label :isconfirmed %><br />
    <%= f.check_box :isconfirmed %>
  </div>
  <div class="field">
    <%= f.label :isreadytohire %><br />
    <%= f.check_box :isreadytohire %>
  </div>
  <div class="field">
    <%= f.label :ishireconfirmed %><br />
    <%= f.check_box :ishireconfirmed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resource_schedules/_list.html.erb
<% if @myresource_schedules.count > 0 %>

<b><div id="mySchedules_header" style="cursor:pointer;text-decoration:underline;">My Listings</div></b>
<br/>

<div id="mySchedules" style="display:none;">
	<table class="table">
	<tr>
	<th>From</th>
	<th>To</th>
	<th>When</th>
	</tr>
	<% @myresource_schedules.each do |resource_schedule| %>
	<tr>
		<td> <%= resource_schedule.startplace %> </td>
		<td> <%= resource_schedule.destination %> </td>
		<td> <%= resource_schedule.starttime %> </td> 
		<td> <%= link_to image_tag("search_icon.jpg"), startsearch_path(:listid => resource_schedule.id, :q => params[:q])%></td> 
	</tr>
	<% end %>
</div>


<%end%>

app/views/resource_schedules/_passresults.html.erb
<h4><%= pluralize(@results.count,"Match") %> Found</h4> <br/>

  <table class="table  table-striped">
    <tr>
      <th>&nbsp;</th>
      <th>Name</th>
<!--       <th>Isowner</th>
 -->
      <th>From</th>
      <th>To</th>
      <th>Start Time</th>
      
      <th>Seat(s) Available</th>
      <th>Ready to hire</th>
      <th></th>
    </tr>

  <% @results.each do |r| %>
    <tr>
      <td><%= image_tag(r.user.image_url, :height=>35, :width=>35) %></td>
      <td><a href="<%='http://www.facebook.com/'+r.user.uid%>" target="_blank"><i class="icon-facebook-sign"></i></a> &nbsp;<%= r.user.name %></td>
<!--       <td>
        <% if r.isowner == 0 %>
          <%= image_tag("Close-2-icon.png") %>
        <%else%>
          <%= image_tag("Ok-icon.png") %>
        <%end%>
      </td>
 -->
      <td><%= r.startplace %></td>
      <td><%= r.destination %></td>
      <td><%= r.starttime %></td>
      <td><%= r.available %></td>
      <% if r.isreadytohire == true %>
        <td>Yes</td>
      <%else%>
        <td>No</td>
      <%end%>
      <td><a href="#" class="btn btn-danger active"><i class="icon-white icon-play"></i> Request</a></td>
    </tr>
  <% end %>
  </table>

app/views/resource_schedules/_passsearch.html.erb
<h3>  </h3>
<%= form_for(@resource_schedule, url: findpassenger_path) do |f| %>
<% @areas = getAreas %>
  <%= hidden_field_tag :isPassenger, "1" %>
      From <%= select_tag(:startplace, options_for_select(@areas, @defstartplace)) %>
      To <%= select_tag(:destination, options_for_select(@areas, @defdest)) %>
      At  
      <div id="datepicker1" class="input-append date">
	      <input data-format="dd/MM/yyyy" type="text" id="resource_schedule_startdate" name="resource_schedule_startdate" size="20" style="width:80px" value="<%= @defdate %>"></input>
        <span class="add-on">
          <i data-time-icon="icon-time" data-date-icon="icon-calendar">
          </i>
        </span>
      </div>
      <div id="timepicker1" class="input-append date">
        <input data-format="hh:mm" type="text" id="resource_schedule_starttime" name="resource_schedule_starttime" style="width:90px" value="<%= @deftime %>"></input>
        <span class="add-on">
          <i data-time-icon="icon-time" data-date-icon="icon-calendar">
          </i>
        </span>
      </div> &nbsp;&nbsp;
  Available <input id="resource_schedule_available" name="resource_schedule[available]" size="30" style="width:30px" type="text">
  <input id="resource_schedule_isacnonac" name="resource_schedule_isacnonac" type="checkbox" value="1"> AC Car


<%= link_to image_tag("search_icon.jpg"), '', :onclick => 'searchFired();', :remote => true %>
<br>
<p class="text-left text-info">If you don't find any results that match your liking, please add your request for others to find you.</p><input name="commit" class="pull right btn btn-primary" type="submit" value="Add this search to Listings">
<% end %>

app/views/resource_schedules/_result.html.erb
<% if @results.count > 0 %>
	<% if @searchcriteria == "car" %>
		<%= render :partial => 'carresults' %>
	<% else %>
		<%= render :partial => 'passresults' %>
	<% end %>
<% else %>
  No matching results <br/><br/>
<% end %>

app/views/resource_schedules/_search.html.erb
<%= form_for(@resource_schedule, url: findcar_path) do |f| %>
<% @areas = getAreas %>
<%= hidden_field_tag :isPassenger, "0" %>

From <%= select_tag(:startplace, options_for_select(@areas, @defstartplace)) %>
To <%= select_tag(:destination, options_for_select(@areas, @defdest)) %>
      At  
      <div id="datepicker1" class="input-append date">
        <input data-format="dd/MM/yyyy" type="text" id="resource_schedule_startdate" name="resource_schedule_startdate" size="20" style="width:80px" value="<%= @defdate %>"></input>
        <span class="add-on">
          <i data-time-icon="icon-time" data-date-icon="icon-calendar">
          </i>
        </span>
      </div>
      <div id="timepicker1" class="input-append date">
        <input data-format="hh:mm" type="text" id="resource_schedule_starttime" name="resource_schedule_starttime" style="width:90px" value="<%= @deftime %>"></input>
        <span class="add-on">
          <i data-time-icon="icon-time" data-date-icon="icon-calendar">
          </i>
        </span>
      </div> &nbsp;&nbsp;
      Ready to Hire Cab?  <input id="resource_schedule_isreadytohire" style="" name="resource_schedule[isreadytohire]" type="checkbox" value="1"> 


<%= link_to image_tag("search_icon.jpg"), '', :onclick => 'searchFired();', :remote => true %>
<br>

<p class="text-left text-info">If you don't find any results that match your liking, please add your request for others to find you.</p><input name="commit" class="pull right btn btn-primary" type="submit" value="Add this search to Listings">
<% end %>

app/views/resource_schedules/find.js.erb
$('#search_div').html('<%= escape_javascript render 'result', locals: { :resource_schedule => @resource_schedule, :results => @results, :searchcriteria => @searchcriteria } %>');

app/views/resource_schedules/findcar.html.erb
<h1>Find Car</h1>
<%= render :partial => 'search' %>
<%= render :partial => 'results' %>

app/views/resource_schedules/findpass.html.erb
<h1>Find Passenger</h1>
<table>
	<tr>
		<td>
			<%= render :partial => 'list' %>
		</td>
		<td>
			<%= render :partial => 'passsearch' %>
			<br>
			<%= render :partial => 'passresults' %>
			
		</td>
	</tr>
</table>

app/views/resource_schedules/index.html.erb
<h1>Listing resource_schedules</h1>

<table>
  <tr>
    <th>Userresourceid</th>
    <th>Userid</th>
    <th>Isowner</th>
    <th>Startplace</th>
    <th>Destination</th>
    <th>Starttime</th>
    <th>Routeno</th>
    <th>Available</th>
    <th>Isconfirmed</th>
    <th>Isreadytohire</th>
    <th>Ishireconfirmed</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @resource_schedules.each do |resource_schedule| %>
  <tr>
    <td><%= resource_schedule.userResourceId %></td>
    <td><%= resource_schedule.userId %></td>
    <td><%= resource_schedule.isowner %></td>
    <td><%= resource_schedule.startplace %></td>
    <td><%= resource_schedule.destination %></td>
    <td><%= resource_schedule.starttime %></td>
    <td><%= resource_schedule.routeno %></td>
    <td><%= resource_schedule.available %></td>
    <td><%= resource_schedule.isconfirmed %></td>
    <td><%= resource_schedule.isreadytohire %></td>
    <td><%= resource_schedule.ishireconfirmed %></td>
    <td><%= link_to 'Show', resource_schedule %></td>
    <td><%= link_to 'Edit', edit_resource_schedule_path(resource_schedule) %></td>
    <td><%= link_to 'Destroy', resource_schedule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Resource schedule', new_resource_schedule_path %>

app/views/resource_schedules/new.html.erb
<h1>New resource_schedule</h1>

<%= render 'form' %>

<%= link_to 'Back', resource_schedules_path %>

app/views/resource_schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Userresourceid:</b>
  <%= @resource_schedule.userResourceId %>
</p>

<p>
  <b>Userid:</b>
  <%= @resource_schedule.userId %>
</p>

<p>
  <b>Isowner:</b>
  <%= @resource_schedule.isowner %>
</p>

<p>
  <b>Startplace:</b>
  <%= @resource_schedule.startplace %>
</p>

<p>
  <b>Destination:</b>
  <%= @resource_schedule.destination %>
</p>

<p>
  <b>Starttime:</b>
  <%= @resource_schedule.starttime %>
</p>

<p>
  <b>Routeno:</b>
  <%= @resource_schedule.routeno %>
</p>

<p>
  <b>Available:</b>
  <%= @resource_schedule.available %>
</p>

<p>
  <b>Isconfirmed:</b>
  <%= @resource_schedule.isconfirmed %>
</p>

<p>
  <b>Isreadytohire:</b>
  <%= @resource_schedule.isreadytohire %>
</p>

<p>
  <b>Ishireconfirmed:</b>
  <%= @resource_schedule.ishireconfirmed %>
</p>


<%= link_to 'Edit', edit_resource_schedule_path(@resource_schedule) %> |
<%= link_to 'Back', resource_schedules_path %>

app/views/resource_schedules/startsearch.html.erb
<br/>
<br/>
<div class="row-fluid" style="display:inline-block; vertical-align: middle">
    <div class="span12">
        <span style="padding:5px">
            <% if @searchcriteria == "car" %>
    	       <a href="/search?q=fc" class="btn btn-primary btn-large active"><img src="/assets/icon_HireACar.png"> Find Cars</a>
            <%else%>
                <a href="/search?q=fc" class="btn btn-success btn-large active"><img src="/assets/icon_HireACar.png"> Find Cars</a>
            <%end%>
        </span>
        <span style="padding:5px">
            <% if @searchcriteria == "pass" %>
                <a href="/search?q=fp" class="btn btn-large  btn-primary active"><img src="/assets/icon_HirePassenger.png"> Find Passengers</a>
            <%else%>
                <a href="/search?q=fp" class="btn btn-large btn-success active"><img src="/assets/icon_HirePassenger.png"> Find Passengers</a>
            <%end%>

        </span>
        <span style="padding:5px">
            <% if @searchcriteria == "group" %>
                <a href="/search?q=gh" class="btn btn-large  btn-primary active"><img src="/assets/icon_GroupHire.png"> Group Hire a Car</a>
            <%else%>
                <a href="/search?q=gh" class="btn btn-large  btn-success active"><img src="/assets/icon_GroupHire.png"> Group Hire a Car</a>
            <%end%>
        </span>
    </div>
 </div>
<br/><br/><br/>
<% if @searchcriteria == "car" %>

    <div class="row-fluid" style="display:inline-block; vertical-align: middle">
        <div class="span12">
            <div class="page-header">
                    <h1>
                        <small>Find cars for your commute</small>
                    </h1>
            </div>
        </div>
    </div>    

	<%= render :partial => 'search' %>

<% elsif @searchcriteria == "pass" %>

    <div class="row-fluid" style="display:inline-block; vertical-align: middle">
        <div class="span12">
            <div class="page-header">
                    <h1>
                        <small>Find passengers to accompany you in your commute</small>
                    </h1>
            </div>
        </div>
    </div>    
	<%= render :partial => 'passsearch' %>
<% else%>
    <div class="row-fluid" style="display:inline-block; vertical-align: middle">
        <div class="span12">
            <div class="page-header">
                    <h1>
                        <small>Find other passengers who do not have a car and hire a car together.</small>
                    </h1>
            </div>
        </div>
    </div>    
    <%= render :partial => 'passsearch' %>
<% end %> 	
	<br/><br/>


<div id="search_div">
<% if @display == "empty" %>
	<%= render :partial => 'list' %>
<% else %>
	<%= render :partial => 'result' %>
<% end %>
</div>