config/routes.rb
Hackathon13Carpool::Application.routes.draw do
 

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  resources :routes

  resources :resource_schedules

resources :users do
   get 'addResource'

   resources :user_resources do
   end
   resources :preferences
end

  resources :homes do
    get 'register'

    get 'start', :on => :collection
    
  end

  get '/findcar' => 'resource_schedules#findcar', :as => 'findcar' 
  post '/findcar' => 'resource_schedules#searchcar', :as => 'findcar'

  get '/findpassenger' => 'resource_schedules#findpass', :as => 'findpassenger' 
  post '/findpassenger' => 'resource_schedules#searchpass', :as => 'findpassenger'

  get '/search' => 'resource_schedules#startsearch', :as => 'startsearch' 
  get '/find' => 'resource_schedules#find', :as => 'find' 
  post '/find' => 'resource_schedules#find', :as => 'find' 
  

   root :to => 'homes#index'

end

app/models/user_resource.rb
class UserResource < ActiveRecord::Base
  belongs_to :user
  attr_accessible :acNonac, :carModel, :carNumber, :driverName, :imageUrl, :isOwned, :isSelfDrive, :maxCapacity, :user_id

  validates :carModel, presence: true
  validates :carNumber, presence: true
  validates :maxCapacity, presence: true
  
  validates_inclusion_of :carModel, :in => ['indica', 'Innova', 'Any']

  def carModel
    read_attribute(:carModel)
  end
  def carModel= (value)
    write_attribute(:carModel, value)
  end
end

app/controllers/user_resources_controller.rb
class UserResourcesController < ApplicationController
  # GET /user_resources
  # GET /user_resources.json

    before_filter :get_user

  def get_user
    @user = User.find(params[:user_id])
  end

  # GET /user_resources/1
  # GET /user_resources/1.json
  def show
    @user_resource = UserResource.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user_resource }
    end
  end

  # GET /user_resources/new
  # GET /user_resources/new.json
  def new
    @user_resource = @user.user_resource.new()

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user_resource }
    end
  end

  # GET /user_resources/1/edit
  def edit
    @user_resource = UserResource.find(params[:id])
  end

  # POST /user_resources
  # POST /user_resources.json
  def create
    @user_resource = @user.user_resource.new(params[:user_resource])

    respond_to do |format|
      if @user_resource.save
        format.html { redirect_to user_preferences_path(@user), notice: 'User resource was successfully created.' }
        format.json { render json: @user_resource, status: :created, location: @user_resource }
      else
        format.html { render action: "new" }
        format.json { render json: @user_resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /user_resources/1
  # PUT /user_resources/1.json
  def update
    @user_resource = UserResource.find(params[:id])

    respond_to do |format|
      if @user_resource.update_attributes(params[:user_resource])
        format.html { redirect_to user_preferences_path(@user), notice: 'User resource was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user_resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_resources/1
  # DELETE /user_resources/1.json
  def destroy
    @user_resource = UserResource.find(params[:id])
    @user_resource.destroy

    respond_to do |format|
      format.html { redirect_to user_preferences_path(@user) }
      format.json { head :no_content }
    end
  end
end

app/helpers/user_resources_helper.rb
module UserResourcesHelper
end

app/views/user_resources/_form.html.erb
  <%= form_for @user_resource, :url => user_user_resources_path(@user_resource.user), :html => { :class => 'form-horizontal' } do |f| %>


  <div class="control-group">
    <label class="control-label" for="user_user_resources_attributes_acNonac">A/c or Non A/c</label>
    <div class="controls">
      <%= f.check_box :acNonac, :class => 'check_box'%>
    </div>
  </div>
    <div class="control-group">
    <label class="control-label" for="user_user_resources_attributes_carModel">Preferred Car Model</label>
        <div class="controls">
      <%= f.select :carModel, ['indica', 'Innova', 'Any'], :class => 'select'%>
    </div>
  </div>
    <div class="control-group">
    <label class="control-label" for="user_user_resources_attributes_maxCapacity">Preferred maximum capacity</label>
        <div class="controls">
      <%= f.text_field :maxCapacity, :class => 'text_field'%>
    </div>
  </div>
    <div class="control-group">
    <label class="control-label" for="user_user_resources_attributes_carNumber">Car Number</label>
        <div class="controls">
      <%= f.text_field :carNumber, :class => 'text_field'%>
    </div>
  </div>
      <div class="control-group">
    <label class="control-label" for="user_user_resources_attributes_driverName">Car Number</label>
        <div class="controls">
      <%= f.text_field :driverName, :class => 'text_field'%>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label" for="user_user_resources_attributes_isSelfDrive">Are you going to self drive the car?</label>
    <div class="controls">
      <%= f.check_box :isSelfDrive, :class => 'check_box'%>
    </div>
  </div>
    <div class="control-group">
    <label class="control-label" for="user_user_resources_attributes_isOwned">Are you owner of the car?</label>
    <div class="controls">
      <%= f.check_box :isOwned, :class => 'check_box'%>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                root_path, :class => 'btn' %>
  </div>

  <% end %>

app/views/user_resources/_update.html.erb
  <%= form_for @user_resource, :url => user_user_resource_path(@user_resource.user, @user_resource), :html => { :class => 'form-horizontal' } do |f| %>


  <div class="control-group">
    <label class="control-label" for="user_user_resources_attributes_acNonac">A/c or Non A/c</label>
    <div class="controls">
      <%= f.check_box :acNonac, :class => 'check_box'%>
    </div>
  </div>
    <div class="control-group">
    <label class="control-label" for="user_user_resources_attributes_carModel">Preferred Car Model</label>
        <div class="controls">
      <%= f.select :carModel, ['indica', 'Innova', 'Any'], :class => 'select'%>
    </div>
  </div>
    <div class="control-group">
    <label class="control-label" for="user_user_resources_attributes_maxCapacity">Preferred maximum capacity</label>
        <div class="controls">
      <%= f.text_field :maxCapacity, :class => 'text_field'%>
    </div>
  </div>
    <div class="control-group">
    <label class="control-label" for="user_user_resources_attributes_carNumber">Car Number</label>
        <div class="controls">
      <%= f.text_field :carNumber, :class => 'text_field'%>
    </div>
  </div>
      <div class="control-group">
    <label class="control-label" for="user_user_resources_attributes_driverName">Car Number</label>
        <div class="controls">
      <%= f.text_field :driverName, :class => 'text_field'%>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label" for="user_user_resources_attributes_isSelfDrive">Are you going to self drive the car?</label>
    <div class="controls">
      <%= f.check_box :isSelfDrive, :class => 'check_box'%>
    </div>
  </div>
    <div class="control-group">
    <label class="control-label" for="user_user_resources_attributes_isOwned">Are you owner of the car?</label>
    <div class="controls">
      <%= f.check_box :isOwned, :class => 'check_box'%>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                root_path, :class => 'btn' %>
  </div>

  <% end %>

app/views/user_resources/edit.html.erb
<%- model_class = UserResource -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'update' %>

app/views/user_resources/index.html.erb
<%- model_class = UserResource -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:acNonac) %></th>
      <th><%= model_class.human_attribute_name(:carModel) %></th>
      <th><%= model_class.human_attribute_name(:maxCapacity) %></th>
      <th><%= model_class.human_attribute_name(:imageUrl) %></th>
      <th><%= model_class.human_attribute_name(:carNumber) %></th>
      <th><%= model_class.human_attribute_name(:isOwned) %></th>
      <th><%= model_class.human_attribute_name(:driverName) %></th>
      <th><%= model_class.human_attribute_name(:isSelfDrive) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @user_resources.each do |user_resource| %>
      <tr>
        <td><%= link_to user_resource.id, user_resource_path(user_resource) %></td>
        <td><%= user_resource.user_id %></td>
        <td><%= user_resource.acNonac %></td>
        <td><%= user_resource.carModel %></td>
        <td><%= user_resource.maxCapacity %></td>
        <td><%= user_resource.imageUrl %></td>
        <td><%= user_resource.carNumber %></td>
        <td><%= user_resource.isOwned %></td>
        <td><%= user_resource.driverName %></td>
        <td><%= user_resource.isSelfDrive %></td>
        <td><%=l user_resource.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_resource_path(user_resource), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_resource_path(user_resource),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_resource_path,
            :class => 'btn btn-primary' %>

app/views/user_resources/new.html.erb
<%- model_class = UserResource -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/user_resources/show.html.erb
<%- model_class = UserResource -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @user_resource.user_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:acNonac) %>:</strong></dt>
  <dd><%= @user_resource.acNonac %></dd>
  <dt><strong><%= model_class.human_attribute_name(:carModel) %>:</strong></dt>
  <dd><%= @user_resource.carModel %></dd>
  <dt><strong><%= model_class.human_attribute_name(:maxCapacity) %>:</strong></dt>
  <dd><%= @user_resource.maxCapacity %></dd>
  <dt><strong><%= model_class.human_attribute_name(:imageUrl) %>:</strong></dt>
  <dd><%= @user_resource.imageUrl %></dd>
  <dt><strong><%= model_class.human_attribute_name(:carNumber) %>:</strong></dt>
  <dd><%= @user_resource.carNumber %></dd>
  <dt><strong><%= model_class.human_attribute_name(:isOwned) %>:</strong></dt>
  <dd><%= @user_resource.isOwned %></dd>
  <dt><strong><%= model_class.human_attribute_name(:driverName) %>:</strong></dt>
  <dd><%= @user_resource.driverName %></dd>
  <dt><strong><%= model_class.human_attribute_name(:isSelfDrive) %>:</strong></dt>
  <dd><%= @user_resource.isSelfDrive %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              user_resources_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_resource_path(@user_resource), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_resource_path(@user_resource),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>