config/routes.rb
Hackathon13Carpool::Application.routes.draw do
 

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  resources :routes

  resources :resource_schedules

resources :users do
   get 'addResource'

   resources :user_resources do
   end
   resources :preferences
end

  resources :homes do
    get 'register'

    get 'start', :on => :collection
    
  end

  get '/findcar' => 'resource_schedules#findcar', :as => 'findcar' 
  post '/findcar' => 'resource_schedules#searchcar', :as => 'findcar'

  get '/findpassenger' => 'resource_schedules#findpass', :as => 'findpassenger' 
  post '/findpassenger' => 'resource_schedules#searchpass', :as => 'findpassenger'

  get '/search' => 'resource_schedules#startsearch', :as => 'startsearch' 
  get '/find' => 'resource_schedules#find', :as => 'find' 
  post '/find' => 'resource_schedules#find', :as => 'find' 
  

   root :to => 'homes#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable,
  :lockable, :omniauthable, :omniauth_providers => [:facebook]

  attr_accessible :email, :password,:remember_me,:password_confirmation
  attr_accessible :provider, :uid, :name, :role_ids, :mobile, :image_url
  attr_accessible :preference_attributes, :user_resources_attributes
  has_one :preference
  has_many :user_resource 
  has_many :venues
  has_many :reviews
  has_and_belongs_to_many :roles

  accepts_nested_attributes_for :preference, :user_resource

  validates :name, :presence => true

 	def self.find_for_facebook_oauth(access_token, signed_in_resource=nil)
 		
		user = User.where(:email => access_token.info.email).first
		
	  	unless user
	    	user = User.create(name:access_token.extra.raw_info.name,
	                         provider:access_token.provider,
	                         uid:access_token.uid,
	                         email:access_token.info.email,
	                         image_url:'http://graph.facebook.com/'+access_token.uid+'/picture?width=35&height=35',
	                         password:Devise.friendly_token[0,20]
	                         )

	    	
	  	end
  		user
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end


  def addResource
    @user = User.find(params[:user_id])
    @resource = @user.user_resource.new()
    
    respond_to do |format|
      format.js # start.html.erb
    end
end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
    <%= form_for @resource, :url => user_user_resources_path(@resource.user), :html => { :class => 'form-horizontal' } do |f| %>
    <div class="control-group">
    <label class="control-label" for="user_user_resources_attributes_acNonac">A/c</label>
    <div class="controls">
      <%= f.check_box :acNonac, :class => 'check_box'%>
    </div>
  </div>
    <div class="control-group">
    <label class="control-label" for="user_user_resources_attributes_carModel">Preferred Car Model</label>
        <div class="controls">
      <%= f.select :carModel, ['indica', 'Innova', 'Any'], :class => 'select'%>
    </div>
  </div>
    <div class="control-group">
    <label class="control-label" for="user_user_resources_attributes_maxCapacity">Preferred maximum capacity</label>
        <div class="controls">
      <%= f.text_field :maxCapacity, :class => 'text_field'%>
    </div>
  </div>
    <div class="control-group">
    <label class="control-label" for="user_user_resources_attributes_carNumber">Car Number</label>
        <div class="controls">
      <%= f.text_field :carNumber, :class => 'text_field'%>
    </div>
  </div>
      <div class="control-group">
    <label class="control-label" for="user_user_resources_attributes_driverName">Driver Name</label>
        <div class="controls">
      <%= f.text_field :driverName, :class => 'text_field'%>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label" for="user_user_resources_attributes_isSelfDrive">Are you going to self drive the car?</label>
    <div class="controls">
      <%= f.check_box :isSelfDrive, :class => 'check_box'%>
    </div>
  </div>
    <div class="control-group">
    <label class="control-label" for="user_user_resources_attributes_isOwned">Are you owner of the car?</label>
    <div class="controls">
      <%= f.check_box :isOwned, :class => 'check_box'%>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                root_path, :class => 'btn' %>
  </div>

  <% end %>

app/views/users/addResource.js.erb
$('#resourceList').append('<%= escape_javascript render 'form', locals: { :user => @user } %>');

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>