config/routes.rb
Hackathon13Carpool::Application.routes.draw do
 

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  resources :routes

  resources :resource_schedules

resources :users do
   get 'addResource'

   resources :user_resources do
   end
   resources :preferences
end

  resources :homes do
    get 'register'

    get 'start', :on => :collection
    
  end

  get '/findcar' => 'resource_schedules#findcar', :as => 'findcar' 
  post '/findcar' => 'resource_schedules#searchcar', :as => 'findcar'

  get '/findpassenger' => 'resource_schedules#findpass', :as => 'findpassenger' 
  post '/findpassenger' => 'resource_schedules#searchpass', :as => 'findpassenger'

  get '/search' => 'resource_schedules#startsearch', :as => 'startsearch' 
  get '/find' => 'resource_schedules#find', :as => 'find' 
  post '/find' => 'resource_schedules#find', :as => 'find' 
  

   root :to => 'homes#index'

end

app/models/route.rb
class Route < ActiveRecord::Base
  attr_accessible :area, :routeindex, :routeno
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  # GET /routes
  # GET /routes.json
  def index
    @routes = Route.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @routes }
    end
  end

  # GET /routes/1
  # GET /routes/1.json
  def show
    @route = Route.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @route }
    end
  end

  # GET /routes/new
  # GET /routes/new.json
  def new
    @route = Route.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @route }
    end
  end

  # GET /routes/1/edit
  def edit
    @route = Route.find(params[:id])
  end

  # POST /routes
  # POST /routes.json
  def create
    @route = Route.new(params[:route])

    respond_to do |format|
      if @route.save
        format.html { redirect_to @route, notice: 'Route was successfully created.' }
        format.json { render json: @route, status: :created, location: @route }
      else
        format.html { render action: "new" }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /routes/1
  # PUT /routes/1.json
  def update
    @route = Route.find(params[:id])

    respond_to do |format|
      if @route.update_attributes(params[:route])
        format.html { redirect_to @route, notice: 'Route was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /routes/1
  # DELETE /routes/1.json
  def destroy
    @route = Route.find(params[:id])
    @route.destroy

    respond_to do |format|
      format.html { redirect_to routes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/views/routes/_form.html.erb
<%= form_for(@route) do |f| %>
  <% if @route.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@route.errors.count, "error") %> prohibited this route from being saved:</h2>

      <ul>
      <% @route.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :routeno %><br />
    <%= f.number_field :routeno %>
  </div>
  <div class="field">
    <%= f.label :routeindex %><br />
    <%= f.number_field :routeindex %>
  </div>
  <div class="field">
    <%= f.label :area %><br />
    <%= f.text_field :area %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/routes/edit.html.erb
<h1>Editing route</h1>

<%= render 'form' %>

<%= link_to 'Show', @route %> |
<%= link_to 'Back', routes_path %>

app/views/routes/index.html.erb
<h1>Listing routes</h1>

<table>
  <tr>
    <th>Routeno</th>
    <th>Routeindex</th>
    <th>Area</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @routes.each do |route| %>
  <tr>
    <td><%= route.routeno %></td>
    <td><%= route.routeindex %></td>
    <td><%= route.area %></td>
    <td><%= link_to 'Show', route %></td>
    <td><%= link_to 'Edit', edit_route_path(route) %></td>
    <td><%= link_to 'Destroy', route, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Route', new_route_path %>

app/views/routes/new.html.erb
<h1>New route</h1>

<%= render 'form' %>

<%= link_to 'Back', routes_path %>

app/views/routes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Routeno:</b>
  <%= @route.routeno %>
</p>

<p>
  <b>Routeindex:</b>
  <%= @route.routeindex %>
</p>

<p>
  <b>Area:</b>
  <%= @route.area %>
</p>


<%= link_to 'Edit', edit_route_path(@route) %> |
<%= link_to 'Back', routes_path %>